name: Lint, Check Types, Build
on: push

jobs:
  lint-check-types-and-build:
    name: Lint, Check Types, Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install dependencies
        # TODO: Switch to `pnpm install` option to fail on
        # ignored build scripts, when it exists:
        # - https://github.com/pnpm/pnpm/issues/9032#issuecomment-2647428724
        # run: pnpm install --<flag here>
        run: pnpm install | while IFS= read -r line; do echo "$line"; echo "$line" | grep -q 'Ignored build scripts:' && false; done
      - run: pnpm eslint . --max-warnings 0
      - run: pnpm tsc
      - run: pnpm tsc --project tsconfig.node.json --noEmit
      - name: Build extension
        run: pnpm build
